#! /usr/bin/env bash

# To run on the instance

export PATH=$PATH:$(pwd)
java -cp middleware-1.0.0-SNAPSHOT-jar-with-dependencies.jar pt.ulisboa.tecnico.cnv.middleware.WebServer &> /tmp/middleware.log &
disown
